### ISSUE TITLE
Filter classes were removed from ensembldb

### ISSUE THREAD

**Issue by jorainer** [kauralasoo/wiggleplotr#4]
Hi,
sorry for the (too) late heads up! I've removed the filter classes from `ensembldb`, so your package is currently failing on Bioc!
I'll forking the package, fixing it and make a pull request.

**Comment by kauralasoo** [comment]
Resolved in https://github.com/kauralasoo/wiggleplotr/commit/fbfbc1060e646a543d4bde184607441550ecb211
