### ISSUE TITLE
exon labeling

### ISSUE THREAD

**Issue by fifdick** [kauralasoo/wiggleplotr#8]
Hi, im using wiggleplotr to plot transcripts and it works very nicely for me.
I was wondering if there would be a possibility to add exon labeling to the plot, i.e. numbering of the exons. Such that when comparing different isoforms of one gene one could immediately see which exon is missing in one isoform for example.

**Comment by kauralasoo** [comment]
Hi,
That's a very good question! Unfortunately this is currently not implemented, but with some effort you could compose such plot yourself. If you call the plotCoverage() function with the parameter return_subplots_list = TRUE, then it returns a list of two ggplot objects - one containing the coverage plot and the other one containing the genomic (transcript) annotations. Internally, plotCoverage() uses cowplot::plot_grid() function to paste these two plots together (see line 261 in here: https://github.com/kauralasoo/wiggleplotr/blob/master/R/wiggleplotr.R#L261)

So what you could do is:
1. Use plotCoverage() function with return_subplot_list = TRUE to make the read coverage plot.
2. Modify the plotTranscripts() function to add exon identifiers and make a new transcript annotations plot.
3. Use cowplot::plot_grid() to paste the two plots together.

I do appreciate that Step 2 might be quite complicated.

Best,
Kaur

**Comment by fifdick** [comment]
Hi, thanks for the quick reply. I actually am not in need of the coverage
plot. I just like the transcript plots since you offer the nice intron
scaling option.
but yes Ill try to include it into plotTranscripts().
Thanks anyways.


Am Di., 30. Apr. 2019 um 10:27 Uhr schrieb Kaur Alasoo <
notifications@github.com>:
