### ISSUE TITLE
Plot transcripts from GTF

### ISSUE THREAD

**Issue by fursham-h** [kauralasoo/wiggleplotr#9]
Hi Kaur,

Hope you are well. Your tool has been very useful for me lately to visualize transcript isoforms.

My input object is typically a Granges object imported from a custom-assembled GTF. It would be nice to have a function to plotTranscriptsFromGTF function that conveniently group the exon and cds features by transcript and plot it out. Users may specify which gene/transcript to plot by providing an argument to filter the GTF by a logical expression (eg gene_name == "Ncoa7"). Unfiltered GTF may not be plotted as transcripts have different seqlevels.

What do you think of this feature? I do have an idea on how to implement it and would like to create a pull request if you think this idea is feasible.

Fursham

**Comment by kauralasoo** [comment]
Hi Fursham,

Sorry for not getting back to you earlier. I think it's a nice idea, but I'm not sure if the wiggleplotr package is the correct venue for it.  Do I understand it correctly, that this would mostly be used by users of the factR package working with custom GTF files? In that case, would it make more sense to add this function to the factR package? Does it depend of internal wiggleplotr functions that have not been exported? If yes, maybe we can export these functions from wiggleplotr and you could use wiggleplotr as a dependency. Alternatively, you could copy the relevant code from wiggleplotr package to your package, if that makes more sense. 

Best
Kaur

**Comment by fursham-h** [comment]
Hi Kaur,

I've written a prototype function for the above motive in my package. It's essentially a wrapper that prepares exons and cds Grangeslist from a gtf, and pass these objects to your plotTranscripts function. It's working great, just using your exported functions.

I'll close this issue then. 
Thanks!
